services:
  
  movies-app:
    build:
      target: development 
    volumes:
      - .:/app         
      - /app/node_modules
    ports:
      - "5173:5173"     
    environment:
      - NODE_ENV=development
    restart: no